### ISSUE TITLE
Interested in working with SynEdit

### ISSUE THREAD

**Issue by embradded** [SynEdit/SynEdit#1]
However, it appears the most current version is up on sourceforge because there is an XE5 project there, and not one here in GitHub.  What is the roadmap of this project?  Has it been fully migrated over to github?  I tried the sourceforge version and could not get some of the demos to compile.  Thanks.

**Comment by CWBudde** [comment]
So far there is no real roadmap beyond some maintenance work. It has fully been migrated to GitHub and it's more or less up to date. It includes packages for recent Delphi versions and all demos should compile out of the box. If you find something that is not working, please create issues for each item one by one.
