### ISSUE TITLE
Delphi XE: [DCC Error] SynHighlighterJava.pas(876): E2011 Low bound exceeds high bound

### ISSUE THREAD

**Issue by tdelphi** [SynEdit/SynEdit#10]
DCC errors when compile revision aff86da4b15030b8d0cc33f4e5e08d461caf0a40 with Delphi XE.
[DCC Error] SynHighlighterJava.pas(876): E2011 Low bound exceeds high bound
[DCC Error] SynHighlighterJava.pas(876): E2011 Low bound exceeds high bound
[DCC Error] SynHighlighterJava.pas(981): E2011 Low bound exceeds high bound
[DCC Error] SynHighlighterJava.pas(981): E2011 Low bound exceeds high bound

Error disappears when replace line 981 text:
    '_', '$', '0'..'9', 'a'..'z', 'A'..'Z', 'Ą'..'Ö', 'Ų'..'ö', 'ų'..'˙':

with
    '_', '$', '0'..'9', 'a'..'z', 'A'..'Z':

Stripping out the 'Ą'..'Ö', 'Ų'..'ö', 'ų'..'˙' block

**Comment by CWBudde** [comment]
This should have been fixed. Please refer to issue #47 for a detailed discussion
