### ISSUE TITLE
eoAutoIndent doesn't work

### ISSUE THREAD

**Issue by kastal** [SynEdit/SynEdit#100]
function TCustomSynEdit.LeftSpacesEx(const Line: string; WantTabs: Boolean; CalcAlways : Boolean = False): Integer;

should be:

function TCustomSynEdit.LeftSpacesEx(const Line: **UnicodeString**; WantTabs: Boolean; CalcAlways : Boolean = False): Integer;

**Comment by CWBudde** [comment]
Fixed
