### ISSUE TITLE
Copy and Paste faults in SynHighlighterSQL.pas

### ISSUE THREAD

**Issue by CodehunterWorks** [SynEdit/SynEdit#112]
Hello!

Please check SynHighlighterSQL.pas at TSynSQLSyn.Create. There are some Copy and Paste faults. E.g. 

`FKeyAttri := TSynHighlighterAttributes.Create(SYNS_AttrReservedWord, SYNS_FriendlyAttrReservedWord);`

should be

`FKeyAttri := TSynHighlighterAttributes.Create(SYNS_AttrKey, SYNS_FriendlyAttrKey);`

and some further Attri are instanced with wrong names. Found until dynamic saving highlighter settings with RTTI in my project.

Greets
Cody

**Comment by Lajos-Juhasz** [comment]
This was not a copy - paste fault. 

Now for the SQL for reserved words is the friendly name Key that makes no sense at all.
