### ISSUE TITLE
SynEditCodeFolding - Typo/Bug in procedure BlockDelimiter

### ISSUE THREAD

**Issue by stbie** [SynEdit/SynEdit#118]
I think there is a typo/bug in DWS and Pascal highlighters for CodeFolding in function **BlockDelimiter**.

Error description:
Block end in commented lines will be detected as valid block end.

Suggested solution:

function BlockDelimiter(Line: Integer): Boolean;
...
    end else if **RE_BlockEnd.Exec**(CurLine) then
    begin
      Index :=  **RE_BlockBegin**.MatchPos[0];
// Should be changed to:
//    Index :=  **RE_BlockEnd**.MatchPos[0];
      if GetHighlighterAttriAtRowCol(LinesToScan, Line, Index) <> fCommentAttri then
...

SynHighlighterDWS - proceudure BlockDelimiter - Line 1042
SynHighlighterPas - proceudure BlockDelimiter - Line 1164

**Comment by pyscripter** [comment]
I can confirm this is correct.
