### ISSUE TITLE
Does not compile in Delphi 6 (but does in Delphi 7), should it?

### ISSUE THREAD

**Issue by dummzeuch** [SynEdit/SynEdit#126]
The current source does not compile with Delphi 6. Should it? There is no explicit mention of supported Delphi versions that I could find.

The (first) problem is in SynEdit.pas, line 1488:
        ExStyle := ExStyle or WS_EX_COMPOSITED;

WS_EX_COMPOSITED is not declared in Delphi 6.

Should Delphi 6 still be supported? The packages for it exist (But there are still also packages for Delphi 6 CLX so this probably doesn't mean much.) I haven't even tried Delphi 5 for which the packages also exist.

**Comment by dummzeuch** [comment]
OK, I just found a pull request for this:

https://github.com/SynEdit/SynEdit/pull/101/commits/335785527d1c59b56b928705f481927da4b12e98

**Comment by CWBudde** [comment]
Merged
