### ISSUE TITLE
EnumUserSettings: support for 64Bit and WOW6432Node

### ISSUE THREAD

**Issue by ase379** [SynEdit/SynEdit#127]
When using the SynHighlighterPas in my application in conjunction with a TSynPasSyn, the function TSynPasSyn.EnumUserSettings iterates though the registry for finding proper delphi versions to be used.
If my application is compiled in 32 bits, everything works fine: The settings for the installed 10.3 RIO IDE are used. If I compile it using 64Bit, the default settings are used.
As the IDE keys are stored in the 32 Bit branch of the registry, the 64 bit process cannot access the registry values. Thus, a fallback to the default is done. See here: https://support.microsoft.com/de-de/help/305097/how-to-view-the-system-registry-by-using-64-bit-versions-of-windows.

So I changed the function like the following:
(I omitted TSynPasSyn.EnumUserSettings.LoadKeyVersions as I did not change it.)

```
procedure TSynPasSyn.EnumUserSettings(DelphiVersions: TStrings);
var
  LWOWNode : string;
begin
  { returns the user settings that exist in the registry }
{$IFNDEF SYN_CLX}
  // See UseUserSettings below where these strings are used
  LWowNode := '';
  if Sizeof(NativeInt) = 8 then
    LWowNode := 'WOW6432Node\';

  LoadKeyVersions('\SOFTWARE\'+ LWOWNode + 'Borland\Delphi', '');
  LoadKeyVersions('\SOFTWARE\'+ LWOWNode + 'Borland\BDS', BDSVersionPrefix);
  LoadKeyVersions('\SOFTWARE\'+ LWOWNode + 'CodeGear\BDS', BDSVersionPrefix);
  LoadKeyVersions('\SOFTWARE\'+ LWOWNode + 'Embarcadero\BDS', BDSVersionPrefix);

{$ENDIF}
end;
```

It now works. Is there a chance to correct the described problem ?

**Comment by Lajos-Juhasz** [comment]
It would be cleaner to write the check as:

{$IFDEF WIN64}
  LWowNode := 'WOW6432Node\';
{$ENDIF}

**Comment by ase379** [comment]
Sure

**Comment by ase379** [comment]
Shall I provide a PR?

**Comment by CWBudde** [comment]
Please go ahead and create that PR, if it's just that I'll merge it as soon as it is done.

**Comment by CWBudde** [comment]
Thanks, if I understand it correctly this patch should do the trick, thus closing this issue.
