### ISSUE TITLE
WordWrap fine-tuning

### ISSUE THREAD

**Issue by attikov** [SynEdit/SynEdit#129]
in procedure TSynWordWrapPlugin.Reset of SynEditWordWrap.pas;

FMaxRowLength should be

  FMaxRowLength := Min(Editor.MaxScrollWidth, Editor.CharsInWindow);

instead of just FMaxRowLength := Editor.CharsInWindow.

Or make MaxRowLength public etc..etc..

**Comment by CWBudde** [comment]
I'm not that much into the wordwrap function so I can oversee all implications of that change. However, it sounds reasonable enough to make the change.
