### ISSUE TITLE
Option scoLimitToMatchedTextAnywhere & MatchTextAnywhere

### ISSUE THREAD

**Issue by jBitHub** [SynEdit/SynEdit#136]
For the option »scoLimitToMatchedTextAnywhere« there is the field »MatchTextAnywhere«?
Shouldn't the »MatchTextAnywhere« field also be set in the SetOptions method?

procedure TSynBaseCompletionProposal.SetOptions
Line 2802
Form.MatchTextAnywhere := scoLimitToMatchedTextAnywhere in Value;

![grafik](https://user-images.githubusercontent.com/39560844/70608798-0c972b00-1c01-11ea-9794-8470feb8370c.png)

**Comment by CWBudde** [comment]
Solved. Thanks for the hint!
