### ISSUE TITLE
Compiler warning on 64 bit

### ISSUE THREAD

**Issue by davidheff** [SynEdit/SynEdit#139]
In SynRegExpr there is this:

```
  {$IFNDEF SYN_COMPILER_24_UP}
  Mask := 0; // prevent compiler warning
  {$ENDIF}
```

This workaround to defeat a bogus compiler warning is find under the 32 bit compiler. However, the 64 bit compiler reports:

> [dcc64 Hint] SynRegExpr.pas(1318): H2077 Value assigned to 'Mask' never used

I'm compiling with XE7, and I infer from the SYN_COMPILER_24_UP conditional that the issue with the 32 bit compiler is resolved in 10.1.

I suggest that the issue can be resolved like this:

```
  {$IFNDEF SYN_COMPILER_24_UP}
  {$IFDEF SYN_WIN32}
  Mask := 0; // prevent compiler warning
  {$ENDIF}
  {$ENDIF}
```

**Comment by CWBudde** [comment]
I applied the proposed solution.
