### ISSUE TITLE
Memory leak "TSynHashEntry" on TSynSqlSyn

### ISSUE THREAD

**Issue by nanocfw** [SynEdit/SynEdit#14]
In the procedure "TSynSQLSyn.InitializeKeywordLists"
"fKeywords.Clear" is not releasing memory objects on the list, change the "fKeywords.Clear" to "fKeywords.DeleteEntries" solves.

Sorry for the English, I'm using google translator.

**Comment by CWBudde** [comment]
Fixed

**Comment by uschuster** [comment]
I do see the fix in commit d69941a7d2d0ed0ef453a0da074c2d6a77a5174e and close this issue.
