### ISSUE TITLE
Issue 127 was fixed using hard coded WOW64 registry key, rather than using KEY_WOW64_32KEY

### ISSUE THREAD

**Issue by davidheff** [SynEdit/SynEdit#140]
See https://github.com/SynEdit/SynEdit/issues/127

The issue here is that the code needs to read out of the 32 bit view of the registry.  The issue was resolved by injecting `WOW6432Node\` into the registry key. This is the incorrect solution to the problem. Whilst it works, it is preferable to open the registry key with the `KEY_WOW64_32KEY` flag.

**Comment by CWBudde** [comment]
So as far as I understand it, a code like:

```
{$ifdef WIN64}
with TBetterRegistry.Create(KEY_ALL_ACCESS + KEY_WOW64_32KEY) do
{$else}
with TBetterRegistry.Create do
{$ENDIF}
```
would be more suitable, right?

**Comment by davidheff** [comment]
The use of + is wrong for bit flags. Should be or. Not that it matters in this case, but you should always use or to combine bit flags.

As for the conditional, it's not needed. In a 32 bit process KEY_WOW64_32KEY is ignored.

One other comment, is KEY_ALL_ACCESS really necessary.

**Comment by CWBudde** [comment]
Thanks for the comments. I have applied and commited the suggestions.
