### ISSUE TITLE
Transient paints can crash application on paste and search/replace

### ISSUE THREAD

**Issue by zencode1** [SynEdit/SynEdit#141]
Application code that makes use of OnPaintTransient can crash/AV when performing a paste or search and replace.  The crash happens when the transient processing code attempts to access TSynEdit.Text.

Here is the simplest way I've found to demonstrate the crash/AV:
- Add TSynEdit, TSynEditSearch, and TButton to form
- Add a handler for OnPaintTransient
- Add the following code:

```
procedure TForm1.Button1Click(Sender: TObject);
begin
  SynEdit1.CaretXY := BufferCoord(1, 1);
  SynEdit1.SearchReplace('a', 'aaaaaaaaaaaaaaaaaaaa', [ssoReplaceAll]);
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  SynEdit1.SearchEngine := SynEditSearch1;
  SynEdit1.Text :=
    'this is a first line a' + #13#10 +
    'this is a second line a' + #13#10 +
    'this is a third line a' + #13#10;
end;

procedure TForm1.SynEdit1PaintTransient(Sender: TObject; Canvas: TCanvas;
  TransientType: TTransientType);
var
  s: string;
begin
  s := (Sender as TSynEdit).Text;
end;
```

The crash happens after two button clicks.  If you comment the code in SynEdit1PaintTransient the crash does not happen.

The fix I've put in place is to inc/dec FPaintTransientLock in TCustomSynEdit.PasteFromClipboard and TCustomSynEdit.SearchReplace.  I will provide a PR for my fix.  My concern is that it isn't a complete fix or the fix isn't in the correct location.

**Comment by CWBudde** [comment]
I have merged the pull request.
