### ISSUE TITLE
SYN_WIN32 does not mean what the code states it means

### ISSUE THREAD

**Issue by davidheff** [SynEdit/SynEdit#143]
There is a mistake in https://github.com/SynEdit/SynEdit/issues/139 (submitted by me, sorry). Consequently the commit which implemented the fix to this issue (https://github.com/SynEdit/SynEdit/commit/7da87986ab3bbaff5f2d616daf7f7a864f2ee610) is wrong.

It stems from the meaning of `SYN_WIN32`. In SynEdit.inc it says:

```
(* SYN_WIN32            : Compilation target is 32-bit Windows                *)
```

However, there are two places where `SYN_WIN32` is defined:

```
{$IFDEF WIN32}
  {$DEFINE SYN_WIN32}
{$ENDIF}
```

and then later

```
{$IFDEF SYN_KYLIX}
  Kylix is no longer supported. Please refer to the branch 'Kylix'
{$ELSE}
  {$DEFINE SYN_WIN32}
{$ENDIF}
```

The net result of this is that `SYN_WIN32` is always defined. 

Because this is so, in my view, the entire codebase could be massively simplified by removing the `SYN_WIN32` conditional, and stripping out all code in the `{$IFNDEF SYN_WIN32}` branches. It's a pure Windows VCL control, you may as well accept that. In my view.

Another consequence is that https://github.com/SynEdit/SynEdit/commit/7da87986ab3bbaff5f2d616daf7f7a864f2ee610 does not fix https://github.com/SynEdit/SynEdit/issues/139 Instead of 

```
{$IFNDEF SYN_COMPILER_24_UP}
{$IFDEF SYN_WIN32}
Mask := 0; // prevent compiler warning
{$ENDIF}
{$ENDIF}
```
it should read

```
{$IFNDEF SYN_COMPILER_24_UP}
{$IFDEF WIN32}
Mask := 0; // prevent compiler warning
{$ENDIF}
{$ENDIF}
```

In fact that's what I wrote when I submitted the issue. That's what I tested. Then a bit later I noticed the `SYN_WIN32` conditional and edited the issue to use that because it seemed the right thing to do.

**Comment by CWBudde** [comment]
No problem. I'll fix the issue and review dropping the SYN_WIN32 as soon as I have more time for it.

**Comment by CWBudde** [comment]
This is hopefully solved with the recent commit (see above)
