### ISSUE TITLE
Contribute enhancements to SynSQLHighlighter

### ISSUE THREAD

**Issue by RyanSmithHE** [SynEdit/SynEdit#146]
I have been using the Delphi and Lazarus versions of SynEdit and its various parts for a long time.
I had to keep a local fork of specifically the SynHighlighterSQL unit because of some shortcomings I was hoping would get fixed over time, but I realize that if someone doesn't contribute it, it won't get fixed, so I'm asking herewith how to contribute the enhancements made, and if you have any special rules for annotating it.

I'm quite intimately familiar with SQL engines, especially SQLite and Postgres. See the short list of enhancements below. They can be seen working in this free tool: https://sqlitespeed.com

In short, the enhancements are:
1. Changing the Double-Quote to signify an Identifier, not a string, as is consistent with the SQL standard and most Engines out there. (Same with MySQL backticks, MSSQL square brackets, etc.)

2. Add a UDF (User-Defined-Functions) keywords list (empty lists) and "tkudfunction" enumeration for it, then added an interface for programmers to Add to the UDF keywords list those UDFs that may exist in the specific versions of the SQL they operate on, avoiding having to fork the high-lighter codebase to do so.

3. Added Data Types list for SQLite too - It was probably foregone because of the weird typing mechanism, but needn't be.

4. Fleshed out the very outdated sets of SQLite, Postgres and MySQL Functions and Keywords in the lists (I've only cared about the ones I use, but could check and update the rest too).

Is there an interest in adding these? If so, in what format and where? Do you have a guide somewhere?

Thank you kindly, 
Ryan

**Comment by RyanSmithHE** [comment]
PS: If the question seems strange, please know I'm using FOSSIL and SVN, not very familiar with GIT - so feel free to educate me in full sentences, as if I'm 5 years old and hearing it for the first time. No offense will be taken.

**Comment by CWBudde** [comment]
The basic idea with git is that everyone can easily make an own fork. This fork can be modified as needed. For every feature/bug you fix, you should do a separate commit (if possible). Once you're done you can use the pull request feature (either from your local fork or from GitHub) to inform others about your changes.

Everyone can then decide whether he wants to use (merge) your changes into their own fork. And so do we for the main repository. If your changes are useful for everyone and well written, chances are high that we integrate it right away. If not or if it requires much work to integrate, it might still be useful for others as the pull requests will be visible for everyone. Maybe someone else wants to separate it further or integrate it, etc.

Regarding source code styling: I always try to keep the code as close as possible to what is written in the [Object Pascal Style Guide](https://edn.embarcadero.com/article/10280). It's not always 100% clear and my styling isn't perfect either, but it's a good guideline.

I hope that helps.
