### ISSUE TITLE
compile errors in Delphi 6

### ISSUE THREAD

**Issue by dummzeuch** [SynEdit/SynEdit#148]
SynEditHighlighter was saved in UTF-8 with BOM which causes a compile error in Delphi 6.
After fixing this, there was another compile error:
Error: Undeclared identifier: 'KEY_WOW64_32KEY'
(I haven't tried it, but I guess this will also cause errors in several of the newer Delphi versions.)

**Comment by dummzeuch** [comment]
Yes: That identifier is not available in Delphi 6 to 2006. Everything compiles fine with Delphi 2007.

**Comment by CWBudde** [comment]
I haven't thought about KEY_WOW64_32KEY not being present in older Delphi versions. This is indeed a problem. However, I wonder why people still use such old Delphi versions. I can still support 2006 to some extent, but Dephi 6?

**Comment by CWBudde** [comment]
The KEY_WOW64_32KEY problem should have been fixed now. Older Delphi versions (beyond Delphi 7) are not supported officially. If you want you can fork and fix this locally. If the changes are not huge and without side effects it's possible to merge the changes back to the original repository.
