### ISSUE TITLE
For Delphi Rio 10.3 CE Update 3 work?

### ISSUE THREAD

**Issue by luizluvizutto** [SynEdit/SynEdit#152]
I installed it normally in **Delphi Rio 10.3 CE Update 3**, but the coloring doesn't work.
Help-me?

**Comment by CWBudde** [comment]
What do you mean with "installed it normally" and what did you try so far? What did you expect?

**Comment by luizluvizutto** [comment]
Thanks for the feedback!
I found my mistake here. In fact, it was already working.
Sorry my English, I'm from Brazil

**Comment by CWBudde** [comment]
No problem, glad you worked it out by your self.

Em caso de problemas também posso oferecer ajuda em português.
