### ISSUE TITLE
[dcc32 Error] SynHighlighterECMAScript.pas: E2011 Low bound exceeds high bound

### ISSUE THREAD

**Issue by DmLam** [SynEdit/SynEdit#162]
There are two identical errors in SynHighlighterECMAScript.pas in methods **TSynECMAScriptSyn.Next** and **TSynECMAScriptSyn.IsIdentChar**
In both cases the problem is in line 
```
case [some expression of type WideChar] of
  ...
    'A'..'Z', 'a'..'z', '_', '$', #$AA, #$B5, #$BA, #$C0..#$D6, #$D8..#$F6,
    #$F8..#$2C1:
end;
```
Errorneous line is the one containing #$F8..#$2C1

Delphi 10.4.1

**Comment by DmLam** [comment]
Copy of #157

**Comment by CWBudde** [comment]
I have merged the pull request. It should work now (haven't checked though, as I don't have a recent Delphi version at hand)
