### ISSUE TITLE
While compiling for RIO 10.3.3 I get the error "Undeclared Identifier"

### ISSUE THREAD

**Issue by alperyazgan** [SynEdit/SynEdit#166]
Here is the problem;

[DCC Error] SynHighlighterCss.pas(578): E2003 Undeclared identifier: 'SYNS_AttrAtRules'
[DCC Fatal Error] pasall.tmp(50): F2063 Could not compile used unit 'SynHighlighterCss.pas'

And yes I could not find any reference for the identifier, I assume that it should exist in the file 'SynEditStrConst.pas' but.

**Comment by pyscripter** [comment]
Thanks.  Will fix this shortly.

**Comment by alperyazgan** [comment]
Let me check it again in case I messed up with the sources of different versions, I will let you know.

**Comment by alperyazgan** [comment]
Really sorry, false alarm as I guessed; wrong versions in search path. There exists no problem, compiled the packages without any error.
