### ISSUE TITLE
XE8 Package does not compile

### ISSUE THREAD

**Issue by billegge** [SynEdit/SynEdit#17]
The XE8 package does not compile for me.  I spent about an hour trying to make it work then gave up and unfortunately downloaded the SynEdit from the GetIt built into XE8.

**Comment by CWBudde** [comment]
Would you mind to test if the latest revision compiles now. If not, please add the compiler output so that we can track down the issue.

**Comment by Oda2** [comment]
CWBudde, the error begins at SynEdit_R package, and compiler directive when compiling the package in Delphi, automatically adds other compilation of policies, for example is the IMPLICITBUILDING adds twice.

If solving the problem of compiler directive, errors occur in the source file SynUnicode.

Compiler message: "[dcc32 Error] SynUnicode.pas (1743): E2010 Incompatible types: 'AnsiChar' and 'Char'"

Thank you!

**Comment by Oda2** [comment]
Delphi XE8 Compilation https://github.com/SynEdit/SynEdit/pull/18
