### ISSUE TITLE
Feature Request: Underline for Spell Checker

### ISSUE THREAD

**Issue by xelnaga64** [SynEdit/SynEdit#173]
![yQlnX](https://user-images.githubusercontent.com/39432041/123857378-e04e1700-d92a-11eb-9a6b-de346e2ccc02.png)

I made a spell checker app however I can't find a way to underline incorrect words as seen in the image.

Is this feature already available? If not, it would be great if this could be added.

**Comment by pyscripter** [comment]
See https://github.com/jrathlev/SynEdit-Spell-Checker/blob/master/SynEditSpell.pas of how this can be done.

**Comment by xelnaga64** [comment]
Thank you pyscripter! You are hero of my day!!!
