### ISSUE TITLE
Delphi 11 compile error in SynHighlighterECMAScript.pas, line 742 and line 828

### ISSUE THREAD

**Issue by frankwu-delphi** [SynEdit/SynEdit#175]
> [dcc32 Error] SynHighlighterECMAScript.pas(742): E2030 Duplicate case label
procedure TSynECMAScriptSyn.Next;
begin
  FTokenPos := Run;
  case FRange of
    rsMultiLineComment: MultiLineCommentProc;
  else
    case FLine[Run] of
      #0:
        NullProc;
      #10:
        LFProc;
      #13:
        CRProc;
      #1..#9, #11, #12, #14..#32:
        SpaceProc;
      '"', #39:
        StringProc;
      '%':
        ModSymbolProc;
      '&':
        AndSymbolProc;
      '.':
        DotProc;
      '/':
        SlashProc;
      '-':
        MinusProc;
      '\':
        BackslashProc;
      '|':
        OrSymbolProc;
      '(', ')':
        SymbolProc;
      '*':
        StarProc;
      '+':
        PlusProc;
      '=':
        EqualsProc;
      '>':
        GreaterProc;
      '<':
        LessProc;
      '!':
        NotProc;
      '?':
        CoalesceProc;
      '^':
        XorSymbolProc;
      '~', ',', '[', ']', ':', ';', '{', '}':
        SymbolProc;
      '0'..'9':
        NumberProc;
      'A'..'Z', 'a'..'z', '_', '$', #$AA, #$B5, #$BA, #$C0..#$D6, #$D8..#$F6,  //<--Line 742
      #$0F8..#$2C1:
        IdentProc;
    else
      UnknownProc;
    end;
  end;
  inherited;
end;

> [dcc32 Error] SynHighlighterECMAScript.pas(828): E2030 Duplicate case label
function TSynECMAScriptSyn.IsIdentChar(AChar: WideChar): Boolean;
begin
  case AChar of
    'A'..'Z', 'a'..'z', '_', '$',{#$AA, #$B5, #$BA, #$C0..#$D6, #$D8..#$F6, //<--Line 828
    #$0F8..#$2C1:
      Result := True;
    else
      Result := False;
  end;
end;

**Comment by laoqiuqiu** [comment]
try add this
{$HIGHCHARUNICODE ON}

**Comment by frankwu-delphi** [comment]
> try add this
> {$HIGHCHARUNICODE ON}

thx, it works perfect now.
