### ISSUE TITLE
onPaintTransient - strange behavior

### ISSUE THREAD

**Issue by SergSni** [SynEdit/SynEdit#178]
I have discovered a such thing:
- just open OnPaintTransientDemo project
- add to the event
procedure TForm1.EditorPaintTransient(Sender: TObject; Canvas: TCanvas;  TransientType: TTransientType);
...
begin
**MessageBeep(MB_ICONASTERISK);**
  if TSynEdit(Sender).SelAvail then exit;
..

What do you hear ?
The event is called constantly without any need to redraw SynEdit.
And the frequency is very likely to be synchronized with the blinking of the cursor.
Is it normal ?
It's just a cpu-eating :(

**Comment by pyscripter** [comment]
> And the frequency is very likely to be synchronized with the blinking of the cursor.
> Is it normal ?

Cursor blinking causes WM_Paint to be sent to Synedit.  This is done by the Windows operating system.   SynEdit.Paint calls PaintTransient so the answer is yes.

It may be the case that PaintTransient does not need to be called by SynEdit.Paint.

**Comment by SergSni** [comment]
Thanks for the clarification.
Оne more unpleasant thing - when you highlight finding results. 
Everything is fine until you move to another line by pressing the up-down button.
And then..  you'll see annoying flickering of the highlightings.
Any ideas how to avoid this ?

**Comment by pyscripter** [comment]
> Any ideas how to avoid this ?

Use the Tubropack/SynEdit

**Comment by SergSni** [comment]
What difference between this project and TurboPack ?
In other words, what will I gain and what will I lose in the transition ?

**Comment by SergSni** [comment]
> Use the Tubropack/SynEdit

I got you :)

remove this? //if PaintLock = 0 then
    DoOnPaintTransient(ttAfter);

**Comment by SergSni** [comment]
no comments
