### ISSUE TITLE
TDBSynEdit fails copy to clipboard

### ISSUE THREAD

**Issue by AutoCoder512** [SynEdit/SynEdit#179]
On attempting to use the short cut keys to copy or cut from the TDBSynEdit control on a form it fails with an invalid type cast error.

The issue is in the unit SynEditDataObject and this procedure.
procedure TSynEditDataObject.StreamHTML(Editor: TObject; Stream: TStream);

it uses this type cast:
  Ed := Editor as TSynEdit;
which fails with exception: invalid type cast

changing the line to:
  Ed := Editor as TCustomSynEdit;

corrects the issue.

**Comment by pyscripter** [comment]
You have submitted this to the wrong repository.   
It has now been fixed in the TurboPack fork. 
Please close this issue because it does not apply to this repo.
