### ISSUE TITLE
XE2 packages don't compile

### ISSUE THREAD

**Issue by dummzeuch** [SynEdit/SynEdit#182]
The packages for Delphi XE2 do not compile. The runtime package contains a duplicate section with compiler switches that start with

{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}

but there is only one {$ENDIF} for them. This was introduced with the last commit from christian on 2020-05-18.

But even after fixing this, I get compilation errors in the designtime package

**Comment by uschuster** [comment]
The runtime package compiles again.

However there is another fix for almost all runtime packages necessary to include SynHighlighterECMAScript to make the designtime package compile as well.

**Comment by dummzeuch** [comment]
This has been fixed in the meantime.
