### ISSUE TITLE
SynHighlighterSQL.pas - bug on Property FunctionNames

### ISSUE THREAD

**Issue by marcieldeg** [SynEdit/SynEdit#19]
SynHighlighterSQL.pas
Property FunctionNames not work.
Please fix the method SetFunctionNames.
from:

procedure TSynSQLSyn.SetFunctionNames(const Value: TUnicodeStrings);
begin
  fFunctionNames := Value;
end;

to:

procedure TSynSQLSyn.SetFunctionNames(const Value: TUnicodeStrings);
begin
  fFunctionNames.Assign(Value);
end;

Thanks

**Comment by CWBudde** [comment]
Done
