### ISSUE TITLE
Why is TSynYAMLSyn not registered in SynEditReg.pas?

### ISSUE THREAD

**Issue by davidheff** [SynEdit/SynEdit#200]
I not that `TSynYAMLSyn` isn't registered in [SynEditReg.pas](https://github.com/SynEdit/SynEdit/blob/master/Source/SynEditReg.pas#L186), but `TSynXMLSyn` and `TSynJSONSyn` are. Is this intentional, or is it just a simple omission? Are there other highlighters that aren't registered that should be?

**Comment by pyscripter** [comment]
There is no YAML highlighter in this repo.  You can find one https://github.com/pyscripter/SynEdit.

**Comment by davidheff** [comment]
Thanks for that. So many different forks of this project. Anyway, I've just switched wholesale to the pyscripter one which no doubt is kept well up-to-date. Thanks for your help!

**Comment by pyscripter** [comment]
> So many different forks of this project.

Indeed!  Please see the following for background:

- https://en.delphipraxis.net/topic/3028-synedit-preferred-version/?tab=comments#comment-24291
- https://github.com/TurboPack/SynEdit/discussions/239
