### ISSUE TITLE
SynEdit keeps freezing application randomly

### ISSUE THREAD

**Issue by djjd47130** [SynEdit/SynEdit#206]
I've been having a problem since introducing 'TSynEdit' to two of my applications. In both instances, it freezes up after so much as adding a line break, and sometimes just simple navigation.

Sometimes it snaps out of it after a minute or so. Sometimes never.

Using attached with either 'TSynPasSyn' or 'TSynDwsSyn' highlighters. 

Also using VCL Styles. 

Besides that, basically no customization on the control, besides capturing a few events for basic UI updates.

**Comment by djjd47130** [comment]
Hell, even hitting backspace froze it up this time. This is sorta ridiculous. I suspect it has to do with the "undo" feature. But I'm implementing barely anything. 

![image](https://github.com/SynEdit/SynEdit/assets/8213266/0d103010-4ab5-4f1c-a5fe-2c84f2470d7f)

In this case, at the end of the function FindFilesCount, I had accidentally ended with a semicolon, without including the function result. So I quickly hit backspace and started typing what I needed, but it froze up (again)...

**Comment by PTlaowai** [comment]
When I get odd things like that happening, I throw in a heap of ShowMessage('xxxxx') calls in the KeyPress event handlers in the main unit, relevant highlighter unit, and in the autocompletion unit (where xxxxx = a unique number), which can at least narrow it down.
Not exactly elegant I know, but it works for me :-)

**Comment by djjd47130** [comment]
> When I get odd things like that happening, I throw in a heap of ShowMessage('xxxxx') calls in the KeyPress event handlers in the main unit, relevant highlighter unit, and in the autocompletion unit (where xxxxx = a unique number), which can at least narrow it down. Not exactly elegant I know, but it works for me :-)

Unfortunately, I have basically nothing implemented that can cause this freeze - it's something internal. And it's getting EXTREMELY frustrating. The only event I have is `OnChange`, where I update a status bar to simply show `Modified`. That's literally it. 

I'm trying to write an application here, and I'm spending more time fighting this random freezing than actually getting work done. I can't write script for 5 minutes without it freezing up on me (and losing work). I find it very hard to believe that nobody else has this problem.

**Comment by djjd47130** [comment]
As a test, I disabled the event handler for `OnChage`, just in case I am doing something weird, but the problem persists. Like I go 2-3 minutes with no problems, then I do something like press "Enter" or "Backspace" or even open a different script into the editor, and poof, it freezes.

**Comment by djjd47130** [comment]
As another test, I started a brand new project which consists of ONLY:
- TSynEdit control
- TSynDwsSyn component (Attached to TSynEdit control)

After some testing, the problem STILL persists.

The problem seems to occur after going a period of time without modifying the script - such as at least 30-60 seconds of idle time, or navigating to another application and back. It's not all the time, but quite random. That's the only pattern I've seen so far.

There is literally no code, only DFM, as seen below:


```
object SynDWSSyn1: TSynDWSSyn
  DefaultFilter = 'DWScript Files (*.dws;*.pas;*.inc)|*.dws;*.pas;*.inc'
  CommentAttri.Foreground = clLime
  IdentifierAttri.Foreground = clSilver
  NumberAttri.Foreground = clMoneyGreen
  FloatAttri.Foreground = clMoneyGreen
  StringAttri.Foreground = 14449959
  SymbolAttri.Foreground = clWhite
  Left = 536
  Top = 256
end
object txtScript: TSynEdit
  Left = 0
  Top = 0
  Width = 961
  Height = 433
  Align = alTop
  Color = clBlack
  ActiveLineColor = 3158064
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWhite
  Font.Height = -16
  Font.Name = 'Consolas'
  Font.Style = []
  Font.Quality = fqClearTypeNatural
  TabOrder = 0
  UseCodeFolding = False
  BorderStyle = bsNone
  Gutter.BorderStyle = gbsNone
  Gutter.Color = clBlack
  Gutter.BorderColor = clSilver
  Gutter.Font.Charset = DEFAULT_CHARSET
  Gutter.Font.Color = clWhite
  Gutter.Font.Height = -16
  Gutter.Font.Name = 'Consolas'
  Gutter.Font.Style = []
  Gutter.Font.Quality = fqClearTypeNatural
  Gutter.ShowLineNumbers = True
  Gutter.Gradient = True
  Gutter.GradientStartColor = clBlack
  Gutter.GradientEndColor = 4539717
  Gutter.Bands = <
    item
      Kind = gbkMarks
      Width = 13
    end
    item
      Kind = gbkLineNumbers
    end
    item
      Kind = gbkFold
    end
    item
      Kind = gbkTrackChanges
    end
    item
      Kind = gbkMargin
      Width = 3
    end>
  Highlighter = SynDWSSyn1
  Lines.Strings = (
    'procedure ListFilesInFolder(Dir: String);'
    'var'
    '  F: Array of String;'
    '  X: Integer;'
    'begin'
    '  F:= GetFiles(Dir, '#39'*.avi;*.mp4;*.mkv'#39', True);'
    '  PrintLn('#39'Files found: '#39'+IntToStr(Length(F)));'
    '  for X := 0 to Length(F)-1 do begin'
    '    PrintLn('#39'- '#39'+ExtractFileName(F[X]));'
    '  end;'
    'end;'
    ''
    'ListFilesInFolder('#39'M:\Media\Videos\Movies'#39');')
  Options = [eoAutoIndent, eoDisableScrollArrows, eoDragDropEditing, eoEnhanceHomeKey, eoEnhanceEndKey, eoGroupUndo, eoHideShowScrollbars, eoKeepCaretX, eoShowScrollHint, eoSmartTabDelete, eoTabIndent, eoTabsToSpaces, eoShowLigatures, eoWrapWithRightEdge]
  RightEdge = 70
  RightEdgeColor = 4539717
  ScrollHintColor = 6828847
  SelectedColor.Background = 9201502
  SelectedColor.Alpha = 0.400000005960464500
  TabWidth = 2
  WantTabs = True
end
```

**Comment by djjd47130** [comment]
As another test, I removed the highlighter entirely. So the ONLY thing in this test project is `TSynEdit` itself - no code, nothing else. Took me a little while, but after more testing, it STILL ultimately freezes.

**Comment by djjd47130** [comment]
> As another test, I removed the highlighter entirely. So the ONLY thing in this test project is `TSynEdit` itself - no code, nothing else. Took me a little while, but after more testing, it STILL ultimately freezes.

I left it open, came back 15 minutes later, and it had eventually snapped out of it. But how the hell can I use something that keeps freezing out of nowhere? Next (and final) test for me to try is a plain vanilla `TSynEdit` instance with zero properties modified (tried before but couldn't reproduce).

![image](https://github.com/SynEdit/SynEdit/assets/8213266/909cf03b-2574-444a-92fd-13a198ec7016)

**Comment by djjd47130** [comment]
It just happened again, this time on the *most basic vanilla* test scenario.

![image](https://github.com/SynEdit/SynEdit/assets/8213266/925a958d-6824-4784-9274-5dd021d49974)

Note the line "The goal...", and the caret at the end of that line. After some time randomly testing, I went to insert a line break here, and the app froze up, and snapped out of it after about 30 seconds.

Here is my full DFM:

```
object Form2: TForm2
  Left = 0
  Top = 0
  Caption = 'Form2'
  ClientHeight = 426
  ClientWidth = 766
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object SynEdit1: TSynEdit
    Left = 0
    Top = 0
    Width = 766
    Height = 426
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Consolas'
    Font.Style = []
    Font.Quality = fqClearTypeNatural
    TabOrder = 0
    UseCodeFolding = False
    Gutter.Font.Charset = DEFAULT_CHARSET
    Gutter.Font.Color = clWindowText
    Gutter.Font.Height = -11
    Gutter.Font.Name = 'Consolas'
    Gutter.Font.Style = []
    Gutter.Bands = <
      item
        Kind = gbkMarks
        Width = 13
      end
      item
        Kind = gbkLineNumbers
      end
      item
        Kind = gbkFold
      end
      item
        Kind = gbkTrackChanges
      end
      item
        Kind = gbkMargin
        Width = 3
      end>
    Lines.Strings = (
      'SynEdit1')
    SelectedColor.Alpha = 0.400000005960464500
    ExplicitLeft = 56
    ExplicitTop = 104
    ExplicitWidth = 200
    ExplicitHeight = 150
  end
end
```

And the full PAS:

```
unit uMain;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, SynEdit, SynEditHighlighter,
  SynEditCodeFolding, SynHighlighterDWS;

type
  TForm2 = class(TForm)
    SynEdit1: TSynEdit;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form2: TForm2;

implementation

{$R *.dfm}

end.
```

**Comment by PTlaowai** [comment]
Also try running Resource Monitor which comes with Windows (resmon.exe). Right click on your app's name then "analyze wait chain", may tell you what is causing the unresponsive state.

**Comment by djjd47130** [comment]
I believe I made a mistake - I had two different forks confused...
