### ISSUE TITLE
Declaration of TUnicodeStrings.SaveToFile missing

### ISSUE THREAD

**Issue by HeRoSofty** [SynEdit/SynEdit#24]
In commit 0d9f183f0a6d4dbb2ea6934070dda8f0f86a4147 the implementation of `procedure TUnicodeStrings.SaveToFile(const FileName: TFileName; WithBOM: Boolean);` was merged into Source/SynUnicode.pas but not the respective declaration (see commit 2a0359958fa69a83e135c59ecf9617ae42c865ff)

**Comment by CWBudde** [comment]
Fixed
