### ISSUE TITLE
hindi

### ISSUE THREAD

**Issue by firstfriday** [SynEdit/SynEdit#27]
I don't know why but the hindi languages are not displayed correctly e.g paste the following into the edit field.

सिग्नल डिजिटल / एनालॉग 

the result will have very big gabs and if you highlight chars they swap around.
arabic/chinese chars work.
Does anyone have a solution for this?

**Comment by uschuster** [comment]
Unless someone, who does natively use hindi, provides a fix I do not see a chance for a solution.

SynEdit is designed for monospaced fonts and I do not know if there are monospaced hindi fonts at all. To me it seems that subsequent chars are rendered differently than each char separately. The editor in the RAD Studio IDE behaves also like you describe.

**Comment by CWBudde** [comment]
In order to work with complex script languages you need to enable uniscribe. You can do so by manually defining SYN_UNISCRIBE in your project or by modifying the SynEdit.inc file (near the end).

At the moment it is undefined by default as it is slower.
