### ISSUE TITLE
Latest commit changing TCustomSynEdit.GetWordAtRowCol breaks XE2 and lower

### ISSUE THREAD

**Issue by uschuster** [SynEdit/SynEdit#30]
The latest commit https://github.com/SynEdit/SynEdit/commit/593bfb21105d7837f08575cd381a85ad21f8417a does change TCustomSynEdit.GetWordAtRowCol. That does use Low/High for the string type and that is not compatible with XE2 and lower. I will prepare a pull request unless anyone else is faster.

**Comment by CWBudde** [comment]
Sorry for the incompatibility. I should have tested this better before commiting it.

**Comment by uschuster** [comment]
I have created a pull request with the fix.

**Comment by uschuster** [comment]
Issue was fixed with the merge of commit 3496919248c4a032a75f7ad32a284ec0c8a01e08.
