### ISSUE TITLE
Unicode Characters in RTF Export

### ISSUE THREAD

**Issue by atheg** [SynEdit/SynEdit#36]
Greek characters are not exported correct in RTF export

solution:

function ReplaceReservedChar in SynExportRTF.pas could be changed as follows:

```
function TSynExporterRTF.ReplaceReservedChar(AChar: WideChar): string;
begin
  Result := '';
  case AChar of
    '\': Result := '\';
    '{': Result := '{';
    '}': Result := '}';
  end;
  if Ord(AChar) > 127 then
  begin
    if Ord(AChar) <= 255 then
      Result := '\''' + LowerCase(IntToHex(Ord(AChar), 2))
    else
      // SmallInt type-cast is necessary because RTF
      // uses signed 16-Bit Integer for Unicode characters
      Result := '\u' + IntToStr(SmallInt(AChar)) + '?';
  end;
end;
```

**Comment by uschuster** [comment]
I do not see any issue exporting greek characters to RTF. I have exported "RTF Εξαγωγή" (RTF Export) to RTF and the export with D7, D2007, D2010 and 10.1 Berlin does create the same RTF file that is visually identical with the exported text and the text is encoded as

RTF \u917?\u958?\u945?\u947?\u969?\u947?\u942?

**Comment by CWBudde** [comment]
Please provide more information to the problem or otherwise this issue will be closed

**Comment by atheg** [comment]
I attach a demo unit compiled with Delphi 10.1 Berlin Update 2 in 32 bit, and the wrong RTF that it produces. I also attach the correct RTF file when the above changes are applied

[Unit1.dfm.txt](https://github.com/SynEdit/SynEdit/files/837632/Unit1.dfm.txt)
[Unit1.pas.txt](https://github.com/SynEdit/SynEdit/files/837635/Unit1.pas.txt)

Outputs:
[Wrong RTF.txt](https://github.com/SynEdit/SynEdit/files/837641/Wrong.RTF.txt)
[Correct RTF.txt](https://github.com/SynEdit/SynEdit/files/837642/Correct.RTF.txt)

Thanks

**Comment by CWBudde** [comment]
I just tested the application you provided and on my system the output is identical to Correct RTF.txt. I'm using XE7 and XE2 and I haven't tried other Delphi versions so far. Maybe someone with Delphi 10.1 Update 2 can confirm that it's an issue of the Delphi version.
Or can anyone verify that XE7 or XE2 outputs the wrong rtf? Eventually it's something different than the IDE version then.

**Comment by atheg** [comment]
After a little more research I think I found what the problem is. The conversion depends on the System's default locale. When I set the language for non-Unicode programs to English (United States) everything works as expected (correct) but when I set it to Greek (Greece) and rebuild the project then the output rtf is as my previous post (wrong)

**Comment by CWBudde** [comment]
Sounds reasonable. Can you also elaborate at what point of the code the locale comes into role. It would be interesting to see whether this is something Delphi is responsible for (and whether it needs some sort of a workaround) or wheter this is a bug in the SynEdit code.
Now that you (or we) can reproduce the issue it should be fairly easy to step through the code to see why this happens.

**Comment by atheg** [comment]
Well, the problem lies in the comparison between a widechar and an ansichar. As I see it, in order to compare the two characters, Delphi widens the ansi char taking into account the current system locale. So, the code:

`
var
  c: WideChar;
begin
  c := #917;
  if c < #255 then
    showmessage('less')
  else
    showmessage('greater')
end;
`

behaves differently on systems with different system locales (see a similar post [)](http://stackoverflow.com/questions/14274089/incompatible-char-and-widechar-delphi/14276574#14276574)

So, all of the above lead us to my very first post where I mention that the two lines in SynExportRTF.pas should be changed. In particular, 

the line "if AChar > #127 then"
has to be changed to something like "if Ord(AChar) > 127"

and the line "if AChar <= #255"
has to be changed to something like "if Ord(AChar) <= 255"

**Comment by CWBudde** [comment]
Sounds reasonable. I changed the lines you mentioned in commit 54e12c4f10af39ef36af447d2800f53b57f52c80
(sorry, should have mentioned the issue in the commit message for easier referal).
