### ISSUE TITLE
Is this the official version now?

### ISSUE THREAD

**Issue by vincentparrett** [SynEdit/SynEdit#4]
I'm trying to figure out if this is the official version of synedit, or is the sourceforge version the definative source? I'm ignoring Roman's emb sponsored efforts (do not agree with their approach). I'm happy to see synedit on github (my preferred platform for open source), just trying to gauge whether this is the one that will be maintained or not.

Thx.

**Comment by romankassebaum** [comment]
Why do you not agree with it?

**Comment by vincentparrett** [comment]
because of the stated aim to only support the latest version of delphi.

**Comment by romankassebaum** [comment]
IMO this is better than writing code with tons of ifdefs.

**Comment by vincentparrett** [comment]
Well I guess I'll close this since there was no response from the project owners.
