### ISSUE TITLE
Bad pointer

### ISSUE THREAD

**Issue by NiteSoft** [SynEdit/SynEdit#41]
File: SynDBEdit.pas 
Line 257:

```
procedure TCustomDBSynEdit.CMGetDataLink(var Msg: TMessage); 
begin 
  Msg.Result := Integer(FDataLink); 
end; 
```
FDataLink is object (Pointer Win32 - 4 byte, Win64 - 8 byte). Good code:

```
procedure TCustomDBSynEdit.CMGetDataLink(var Msg: TMessage); 
begin 
  Msg.Result := Winapi.Windows.LRESULT(FDataLink); 
end; 
```

**Comment by uschuster** [comment]
I have committed a fix and tested it without and with the fix with Win64 and FastMM with top down memory allocation. Without the fix the address was wrong and accessing it raised an access violation.
