### ISSUE TITLE
Comments in MS SQL

### ISSUE THREAD

**Issue by igitur** [SynEdit/SynEdit#42]
In MS SQL, this is a valid comment:

``` sql
--select * from table
```

However, SynEdit doesn't highlight it as a comment. Only if a insert a space after the `--` does it recognise it as a comment. In MySQL, the space is required, but not in MS SQL.

PS: I'm using HeidiSQL, while digging through the source, found that it uses SynEdit. I gather that SynEdit is responsible for the tokenising and syntax highlighting, but excuse me if I misunderstood this.

**Comment by uschuster** [comment]
It seems to me that you did not check the behavior with SynEdit from this repository. Please do that.

I cannot repeat the issue and no matter which value I do select for the SQLDialect property.

**Comment by CWBudde** [comment]
I close this issue now as there has been no response so far (probably the behavior was not set properly)

**Comment by igitur** [comment]
My apologies for not responding sooner. I will follow up with HeidiSQL devs.

**Comment by ansgarbecker** [comment]
I'll post more details here, having been noticed about this issue recently, through https://github.com/HeidiSQL/HeidiSQL/issues/549 .

Using the latest master branch, this (minor) issue seems not fixed. I am setting the right dialect when Heidi creates a connection to some MySQL server:

    SynSQLSynUsed.SQLDialect := sqlMySQL

Double-dashed comments without a space are invalid for MySQL, and should not be highlighted as a comment. Currently that's the case, and the user might think he's writing a valid comment, getting a slap in his face when executing it:

![grafik](https://user-images.githubusercontent.com/7986591/53833255-5f63f800-3f88-11e9-991f-656e170a0610.png)

**Comment by anselal** [comment]
@CWBudde the issue still remains unsoved. Can you please take a look at it and apply a patch ?

**Comment by CWBudde** [comment]
Applied

**Comment by ansgarbecker** [comment]
Super, this works! Thanks a lot.

**Comment by anselal** [comment]
nice !! thnx !!
