### ISSUE TITLE
TSynCssSyn freezes

### ISSUE THREAD

**Issue by DmitriNL** [SynEdit/SynEdit#44]
When combining TSynEdit with TSynCssSyn and load the following CSS data, the application freezes without warnings, errors or crashes. I'm using C++ Builder XE3 with the latest TSynEdit. There are no other issues.

<code>@media(max-width:767px)
{  
  div[class^="col-xs"], div[class^="col-sm"], div[class^="col-md"],div[class^="col-lg"], div[class^="nsdiv"] { /*display:inline;*/ display:inline-block; } 
  /*div[class*="nsdiv"] { border:0; }*/  
  div[class^="col-xs"], div[class^="col-sm"], div[class^="col-md"],div[class^="col-lg"] { width:100%; }
}</code>

**Comment by CWBudde** [comment]
I'll have a look at this as I was the one who updated the highlighter about two years ago to display several new features.

**Comment by CWBudde** [comment]
This has been fixed to a degree where it doesn't crash anymore. However, the nested statements (such as the '@media' rule) still need improvements (which itself would require to rewrite several parts of the logic.

**Comment by DmitriNL** [comment]
Thank you for your quick response and action. The application doesn't freeze anymore thank you. I'd like to mention that the syntax isn't colored properly.

**Comment by CWBudde** [comment]
That's what I mentioned with "nested statements" need improvements. Unfortunately the current structure doesn't allow nesting beyond one level. Everything beyond gets screwed to some extend.
This means that you can still do a few tweaks, but if you know the internals you can always construct certain situations that will screw the syntax highlighting.

The important part (the freezing) if this issue has been done. For the incorrect rendering I would suggest to create a new issue in this tracker. It might still require to rewrite some parts, but eventually workarounds might at least improve the situation for your particular use case.

**Comment by DmitriNL** [comment]
Thank you for your effort! :)
