### ISSUE TITLE
Compilation error in SynHighlighterJava

### ISSUE THREAD

**Issue by cfarl** [SynEdit/SynEdit#49]
There is a compilation error int this file, at line 876, in Rad Studio XE6:

'A'..'Z', 'a'..'z', '_', '$', 'À'..'Ö', 'Ø'..'ö', 'ø'..'ÿ': IdentProc;

[DCC Error] SynHighlighterJava.pas(876): E2010 Incompatible types: 'Char' and 'string'

I had to change this line to the following, to compile it:

 'A'..'Z', 'a'..'z', '_', '$': IdentProc; // , 'À'..'Ö', 'Ø'..'ö', 'ø'..'ÿ': IdentProc;

**Comment by DanyMarmur** [comment]
You can just change the file format to ANSI.
Right click in the IDE, File Format, select ANSI.
I suspect this is something that the VCS did when the change was comitted.

**Comment by CWBudde** [comment]
This should now compile without further problems as the items are now written in ascii again (using WideChar(#$....)).
