### ISSUE TITLE
[Need Help] How Create new highlighter

### ISSUE THREAD

**Issue by KametaTech** [SynEdit/SynEdit#52]
How create new highlighter ?

**Comment by uschuster** [comment]
Information are provided in SynGen\Highlighters-HowTo.html and the related programs SynGen and HighlighterDemo can be compiled and do what they should.

**Comment by CWBudde** [comment]
I've just added a wiki page for the highlighter (see https://github.com/SynEdit/SynEdit/wiki/How-to-create-new-highlighters). It contains the same as in the html file, but this allows it to find the content of this file more easily.
