### ISSUE TITLE
Is it possible for FMX?

### ISSUE THREAD

**Issue by dtamade** [SynEdit/SynEdit#71]
Is it possible for FMX?
What time?

**Comment by CWBudde** [comment]
It's probably possible to reuse some code for FMX, but SynEdit itself is very much bound to VCL and Windows at the moment.

**Comment by shaunroselt** [comment]
Are there any plans to port this over to FMX in the near future?

**Comment by CWBudde** [comment]
Not at the moment. As written before, it's currently bound very closely to the VCL and in particular windows functions.

**Comment by ShaunRoselt** [comment]
Look at this: https://github.com/HemulGM/FMXRichMemo
