### ISSUE TITLE
LineModificationstate is not modified when adding a new line

### ISSUE THREAD

**Issue by Memnarch** [SynEdit/SynEdit#74]
When i just hit enter to add new lines, the state of a new line is not set to modified. That might be intentional. But from editors like Delphi-IDE, at least i am, used to see modifications on every changed/added line. WHen i write modifications for the SynEdit, i usually implement a second LineBuffer(Hook the original events) to track extra information. In this very old project(the modification is similar to a current one here at work) i set the modificationstate to newly added lines, too:
https://github.com/Memnarch/D16IDE/blob/master/IDEEdit.pas#L213

**Comment by plpolak** [comment]
I have created a pull request to get this

**Comment by CWBudde** [comment]
Sorry, I missed that. It's merged now.
