### ISSUE TITLE
Direct2D additions break Wine compatibility

### ISSUE THREAD

**Issue by ansgarbecker** [SynEdit/SynEdit#91]
The commit ae47e3bb1d959ebf2e63b6fc8c9977eb2b2e995e causes crashes on Wine, probably due to incomplete Direct2D support in Wine (just guessing):

> Access violation at address 00007FDAA8B23E0A in module 'd2d1.dll'. Read of address 0000000000000000

Callstack ends up in line 4 of `TCustomSynEdit.WMSize`

Perhaps this needs to be reported to the Wine tracker, but I'm unsure?

**Comment by ansgarbecker** [comment]
Here's a proposal for a method to detect whether the application is running in Wine, taken from [Ruminated Rumblings](http://ruminatedrumblings.blogspot.de/2008/04/detecting-virtualized-environment.html):

```pas
function TForm1.IsRunningWine: boolean;
var hnd:THandle;
    wine_get_version: function : pchar; {$IFDEF Win32} stdcall; {$ENDIF}
    wine_unix2fn: procedure (p1:pointer; p2:pointer); {$IFDEF Win32} stdcall; {$ENDIF}
begin
result:=false;
hnd:=LoadLibrary('ntdll.dll');
if hnd>32 then
   begin
   wine_get_version:= GetProcAddress(hnd, 'wine_get_version');
   wine_unix2fn:= GetProcAddress(hnd, 'wine_nt_to_unix_file_name');
   if assigned(wine_get_version) or assigned(wine_unix2fn) then
      result:=true;
   FreeLibrary(hnd);
   end;

end;
```

**Comment by ansgarbecker** [comment]
Wine users can work around that crash, by [overriding the builtin Direct2D library with a native one](https://github.com/HeidiSQL/HeidiSQL/issues/83#issuecomment-375969129).

However, with the current master branch there is now a crash when starting an application on Windows Server 2003, and most probably also on Windows XP. See attached crash report:
[bugreport-d2d-2018-12.txt](https://github.com/SynEdit/SynEdit/files/2678933/bugreport-d2d-2018-12.txt)

**Comment by ansgarbecker** [comment]
I just disabled the `SYN_DirectWrite` directive, which seems to solve the issue:

```
// DirectWrite
{$IFDEF SYN_DELPHI_XE2_UP}
  {.$DEFINE SYN_DirectWrite}
{$ENDIF}
```

**Comment by zedxxx** [comment]
To disable it, I use this command in my build scripts:

`sed -i "s/DEFINE SYN_DirectWrite/UNDEF SYN_DirectWrite/i" $requires/SynEdit/Source/SynEdit.inc`

**Comment by ansgarbecker** [comment]
Nice approach, to have it disabled just before building, without touching the sources permanently.

However, I wonder what noticeable drawbacks it has not to use DirectWrite.
