### ISSUE TITLE
Vertical selection with Shift + Alt + Up/Down Arrow

### ISSUE THREAD

**Issue by joaoduarte19** [SynEdit/SynEdit#92]
Is it possible to implement vertical selection with Shift + Alt + Up Arrow or Down Arrow? I would like something similar to the vertical selection of Notepad ++.
Thank you.

**Comment by Lajos-Juhasz** [comment]
I know this is an old issue. Yes it's possible. Shift+Ctrl+C to turn on Column select when you can select a rectangle and then Shift+Ctrl+N to active normal selection.
